DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS widgets;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT UNIQUE NULL,
  name TEXT UNIQUE NULL,
  email TEXT UNIQUE NULL,
  password TEXT NOT NULL,
  facebookId TEXT NULL
);

CREATE TABLE widgets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL
);

